version: '3'
services:
  api-gateway:
    restart: always
    depends_on:
      - mysql-server
    image: caapim/gateway:9.4.00
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "6G"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - /Users/grean11/Docker_Runtime/APIGateway/gw94/license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    networks:
      - frontend
      - backend
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      SSG_DATABASE_JDBC_URL: "jdbc:mysql://mysql-server:3306/ssg"
      SSG_DATABASE_USER: "root"
      SSG_DATABASE_PASSWORD: "password"
      SSG_CLUSTER_HOST: "gateway.ca.com"
      SSG_CLUSTER_PASSWORD: "clusterpassword"
      SSG_JVM_HEAP: "4g"
      EXTRA_JAVA_ARGS: "-XX:ParallelGCThreads=4 -Dcom.l7tech.bootstrap.autoTrustSslKey=trustAnchor,TrustedFor.SSL,TrustedFor.SAML_ISSUER"

  mysql-server:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: "512M"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ssg
    volumes:
      - /Users/grean11/Docker_Runtime/APIGateway/gw94/mysql-volume:/var/lib/mysql
    networks:
      - backend
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"

  # Database
  db:
    image: mysql:neu
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlfun
      MYSQL_DATABASE: andreas
      MYSQL_USER: andreas
      MYSQL_PASSWORD: mysqlfun
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysqlfun
    networks:
      - backend

  # Layer7 Live Api Creator
  liveapicreator:
    depends_on:
      - db
    image: caliveapicreator/5.2.00
    restart: always
    networks:
      - backend

networks:
  frontend:
  backend:
    external:
      name: backend_internal

volumes:
  db_data:
    external:
      name: mysqldb
